import 'dart:math';

import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../features/change_password/presentation/bloc/change_password_bloc.dart';
import '../../features/forgot_password/data/datasources/forgot_password_data_source.dart';
import '../../features/forgot_password/data/repositories/forgot_password_repository_implementation.dart';
import '../../features/forgot_password/domain/repositories/forgot_password_repository.dart';
import '../../features/forgot_password/domain/usecases/do_forgot_password.dart';
import '../../features/forgot_password/presentation/bloc/forgot_password_bloc.dart';
import '../../features/login/data/datasources/login_data_source.dart';
import '../../features/login/data/repositories/login_repository_implementation.dart';
import '../../features/login/domain/entities/login_entity.dart';
import '../../features/login/domain/repositories/login_repository.dart';
import '../../features/login/domain/usecases/do_login.dart';
import '../../features/login/presentation/bloc/login_bloc.dart';
import '../../features/otp/data/datasources/otp_data_source.dart';
import '../../features/otp/data/repositories/otp_repository_implementation.dart';
import '../../features/otp/domain/repositories/otp_repository.dart';
import '../../features/otp/domain/usecases/validate_otp.dart';
import '../../features/otp/presentation/bloc/otp_bloc.dart';
import '../../features/registration/data/datasources/registration_data_source.dart';
import '../../features/registration/data/repositories/registration_repository_implementation.dart';
import '../../features/registration/domain/repositories/registration_repository.dart';
import '../../features/registration/domain/usecases/do_registration.dart';
import '../../features/registration/presentation/bloc/registration_bloc.dart';
import '../errors/failure.dart';
import '../networks/networks.dart';
import '../shared/data/datasources/banner_data_source.dart';
import '../shared/data/repositories/banner_repository_implementation.dart';
import '../shared/domain/entities/banner_entity.dart' as en;
import '../shared/domain/entities/user_entity.dart';
import '../shared/domain/repositories/banner_repository.dart';
import '../shared/domain/usecases/get_banners.dart';
import '../shared/presentation/blocs/banner/banner_bloc.dart';
import '../shared/presentation/widgets/rounded_container.dart';
import '../statics/statics.dart';

part 'helpers.dart';
part 'locator.dart';
part 'shared_preferences_helper.dart';
part 'validation_helper.dart';
